version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongo_node-${CONTAINER_PREFIX}
    ports:
      - 0.0.0.0:${MONGO_PORT}:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
  mongo-express:
    image: mongo-express
    container_name: mongo_express-${CONTAINER_PREFIX}
    restart: always
    ports:
      - ${EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
volumes:
  data: {}
networks:
  default:
    name: mongodb_network
